# YOLOv5 🚀 by Ultralytics, GPL-3.0 license
# YOLOv5 Continuous Integration (CI) GitHub Actions tests

name: YOLOv5 CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'  # runs at 00:00 UTC every day

jobs:
  Benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        model: [yolov5n]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      #- name: Cache pip
      #  uses: actions/cache@v3
      #  with:
      #    path: ~/.cache/pip
      #    key: ${{ runner.os }}-Benchmarks-${{ hashFiles('requirements.txt') }}
      #    restore-keys: ${{ runner.os }}-Benchmarks-
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r terraform/pysrc/requirements.txt coremltools openvino-dev tensorflow-cpu --extra-index-url https://download.pytorch.org/whl/cpu
          python --version
          pip --version
          pip list
      - name: Run benchmarks
        run: |
          python utils/benchmarks.py --weights ${{ matrix.model }}.pt --img 320

  Tests:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
        model: [yolov5n]
        include:
          - os: ubuntu-latest
            python-version: '3.7'  # '3.6.8' min
            model: yolov5n
          - os: ubuntu-latest
            python-version: '3.8'
            model: yolov5n
          - os: ubuntu-latest
            python-version: '3.10'
            model: yolov5n
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get cache dir
        # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-${{ matrix.python-version }}-pip-
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r terraform/pysrc/requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
          python --version
          pip --version
          pip list
      - name: Check environment
        run: |
          python -c "import utils; utils.notebook_init()"
          echo "RUNNER_OS is $RUNNER_OS"
          echo "GITHUB_EVENT_NAME is $GITHUB_EVENT_NAME"
          echo "GITHUB_WORKFLOW is $GITHUB_WORKFLOW"
          echo "GITHUB_ACTOR is $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY is $GITHUB_REPOSITORY"
          echo "GITHUB_REPOSITORY_OWNER is $GITHUB_REPOSITORY_OWNER"

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Use gcloud CLI
        run: 'gcloud info'
      - name: Action 7z
        uses: edgarrc/action-7z@v1
      - name: Run tests
        shell: bash
        run: |
          # export PYTHONPATH="$PWD"  # to run '$ python *.py' files in subdirectories
          d=cpu  # device
          model=${{ matrix.model }}
          # Detect
          7z x terraform/pysrc/Archive.zip -o /tmp/archive
          cd /tmp/
          ls
          python /tmp/archive/main.py
