name: Terraform plan on gcp
# tfstate in the cloud stuff
# https://stackoverflow.com/questions/64397938/how-to-integrate-terraform-state-into-github-action-workflow

# uploading to gcs
# https://github.com/google-github-actions/upload-cloud-storage

on:
  pull_request:
    branches: [master]


defaults:
  run:
    working-directory: terraform

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@master
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCLOUD_AUTH }}'
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: Use gcloud CLI
      run: 'gcloud info'
    - name: get tfstate and auth files
      shell: bash
      run: |
        # gsutil -m cp -R gs://gh-actions-tf-backend terraform/
        # ls terraform/*
        # cd terraform
        echo "copying the files from GCS"
        gsutil -m cp -R gs://gh-actions-tf-backend/* ./
        echo "current directory and contents: "
        pwd
        ls
    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      with:
       tf_actions_version: 1.2.2
       tf_actions_subcommand: "init"
       tf_actions_working_dir: 'terraform'
    - name: "Terraform Plan"
      uses: hashicorp/terraform-github-actions@master
      with:
       tf_actions_version: 1.2.2
       tf_actions_subcommand: "plan"
       tf_actions_working_dir: 'terraform'
      #  args: -var="client_secret=${{ secrets.clientSecret }}"
      #        -var="client_id=${{ secrets.clientId }}"
      #        -var="tenant_id=${{ secrets.tenantId }}"
      #        -var="sub=${{ secrets.sub }}"

